map_311 = {'SRNumber': 'SRNumber',
           'CreatedDate': 'created_dt',
           'UpdatedDate': 'updated_dt',
           'ActionTaken': 'ActionTaken',
           'Owner': 'owner',
           'RequestType': 'request_t',
           'Status': 'Status',
           'RequestSource': 'RequestSource',
           'MobileOS': 'MobileOS',
           'Anonymous': 'Anonymous',
           'AssignTo': 'AssignTo',
           'ServiceDate': 'service_dt',
           'ClosedDate': 'closed_dt',
           'AddressVerified': 'AddressVerified',
           'ApproximateAddress': 'ApproximateAddress',
           'Address': 'address',
           'HouseNumber': 'HouseNumber',
           'Direction': 'Direction',
           'StreetName': 'street',
           'Suffix': 'Suffix',
           'ZipCode': 'zip_code',
           'Latitude': 'latitude',
           'Longitude': 'longitude',
           'Location': 'location',
           'TBMPage': 'TBMPage',
           'TBMColumn': 'TBMColumn',
           'TBMRow': 'TBMRow',
           'APC': 'APC',
           'CD': 'cd',
           'CDMember': 'cd_member',
           'NC': 'nc',
           'NCName': 'nc_name',
           'PolicePrecinct': 'precinct'
           }

column_subset = ['SRNumber',
                 'created_dt',
                 'updated_dt',
                 'owner',
                 'request_t',
                 'service_dt',
                 'closed_dt',
                 'address',
                 'street',
                 'zip_code',
                 'latitude',
                 'longitude',
                 'location',
                 'APC',
                 'cd',
                 'cd_member',
                 'nc',
                 'nc_name',
                 'precinct']
